# Dados de Veículos Roubados no Estado de São Paulo

Os dados obtidos dessa extração foram no periodo de 2020 de janeiro até dezembro de 2021

# Bibliotecas necessárias

In [1]:
import pandas as pd
import numpy as np
import csv
import statistics
import os
from datetime import datetime

# Covertendo o dataset extraído

In [2]:
data_xls = pd.read_excel('DadosBO_2020_1(ROUBO DE VEÍCULOS).xlsx', 'DadosBO_2020_1', dtype=str, index_col=None)
data_xls.to_csv('csvfile.csv', encoding='utf-8', index=False)

In [3]:
df = pd.read_csv(r'C:\Users\Cassul\Desktop\trabalho_mineracao\csvfile.csv', encoding='utf-8')

In [4]:
df.head()
columns = ['ANO_BO', 'NUM_BO', 'DATAOCORRENCIA', 'HORAOCORRENCIA', 'PERIDOOCORRENCIA', 'DATACOMUNICACAO', 'BO_AUTORIA', 'FLAGRANTE', 'LOGRADOURO', 'NUMERO', 'BAIRRO', 'CIDADE', 'UF', 'LATITUDE', 'LONGITUDE', 'DESCRICAOLOCAL', 'DESCR_TIPO_VEICULO', 'SOLUCAO', 'DELEGACIA_NOME', 'DELEGACIA_CIRCUNSCRICAO', 'ESPECIE', 'RUBRICA', 'DESDOBRAMENTO', 'STATUS', 'QUANT_CELULAR', 'MARCA_CELULAR']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9306 entries, 0 to 9305
Data columns (total 54 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ANO_BO                    9306 non-null   int64
 1   NUM_BO                    9306 non-null   int64
 2   NUMERO_BOLETIM            9306 non-null   object
 3   BO_INICIADO               9306 non-null   object
 4   BO_EMITIDO                9306 non-null   object
 5   DATAOCORRENCIA            9306 non-null   object
 6   HORAOCORRENCIA            8918 non-null   object
 7   PERIDOOCORRENCIA          9306 non-null   object
 8   DATACOMUNICACAO           9306 non-null   object
 9   DATAELABORACAO            9306 non-null   object
 10  BO_AUTORIA                9306 non-null   object
 11  FLAGRANTE                 9306 non-null   object
 12  NUMERO_BOLETIM_PRINCIPAL  1302 non-null   object
 13  LOGRADOURO                8629 non-null   object
 14  NUMERO                    9290 non-null   float64
 15  BAIRRO                    9283 non-null   object
 16  CIDADE                    9290 non-null   object
 17  UF                        9290 non-null   object
 18  LATITUDE                  8477 non-null   float64
 19  LONGITUDE                 8477 non-null   float64
 20  DESCRICAOLOCAL            9306 non-null   object
 21  EXAME                     2372 non-null   object
 22  SOLUCAO                   9306 non-null   object
 23  DELEGACIA_NOME            9306 non-null   object
 24  DELEGACIA_CIRCUNSCRICAO   9306 non-null   object
 25  ESPECIE                   9306 non-null   object
 26  RUBRICA                   9306 non-null   object
 27  DESDOBRAMENTO             1344 non-null   object
 28  STATUS                    9306 non-null   object
 29  TIPOPESSOA                156 non-null    object
 30  VITIMAFATAL               156 non-null    object
 31  NATURALIDADE              91 non-null     object
 32  NACIONALIDADE             87 non-null     object
 33  SEXO                      156 non-null    object
 34  DATANASCIMENTO            95 non-null     object
 35  IDADE                     95 non-null     float64
 36  ESTADOCIVIL               91 non-null     object
 37  PROFISSAO                 74 non-null     object
 38  GRAUINSTRUCAO             9 non-null      object
 39  CORCUTIS                  156 non-null    object
 40  NATUREZAVINCULADA         156 non-null    object
 41  TIPOVINCULO               156 non-null    object
 42  RELACIONAMENTO            0 non-null      float64
 43  PARENTESCO                0 non-null      float64
 44  PLACA_VEICULO             6509 non-null   object
 45  UF_VEICULO                6617 non-null   object
 46  CIDADE_VEICULO            6574 non-null   object
 47  DESCR_COR_VEICULO         6798 non-null   object
 48  DESCR_MARCA_VEICULO       6544 non-null   object
 49  ANO_FABRICACAO            8988 non-null   float64
 50  ANO_MODELO                8374 non-null   float64
 51  DESCR_TIPO_VEICULO        6798 non-null   object
 52  QUANT_CELULAR             0 non-null      float64
 53  MARCA_CELULAR             0 non-null      float64
dtypes: float64(10), int64(2), object(42)
memory usage: 3.8+ MB

In [6]:
df.head()

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,PLACA_VEICULO,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO,QUANT_CELULAR,MARCA_CELULAR
0,2019,10019,10019/2019,2019-12-31 23:52:17,2020-01-01 00:06:39,2019-12-31 00:00:00,22:30:00,A NOITE,2019-12-31 00:00:00,2019-12-31 23:52:17,...,QNY7994,MG,BELO HORIZONTE,Cinza,NISSAN/VERSA 10,2018.0,2018.0,AUTOMOVEL,NaN,NaN
1,2019,1624930,1624930/2019,2020-01-01 00:14:23,2020-01-01 00:14:02,2019-12-31 00:00:00,21:23:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:14:23,...,NaN,SP,NaN,Branco,NaN,NaN,NaN,AUTOMOVEL,NaN,NaN
2,2019,1624930,1624930/2019,2020-01-01 00:14:23,2020-01-01 00:14:02,2019-12-31 00:00:00,21:23:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:14:23,...,FOX1473,SP,POÁ,Preta,I/VW FOX 1.6 PLUS,2004.0,NaN,AUTOMOVEL,NaN,NaN
3,2020,2,2020-02-01 00:00:00,2020-01-01 00:17:24,2020-01-01 00:16:36,2019-12-31 00:00:00,22:00:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:17:24,...,NaN,NaN,NaN,Não Informado,NaN,NaN,NaN,AUTOMOVEL,NaN,NaN
4,2020,2,2020-02-01 00:00:00,2020-01-01 00:17:24,2020-01-01 00:16:36,2019-12-31 00:00:00,22:00:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:17:24,...,ELR4802,SP,MAIRIPORÃ,Prata,FORD/FIESTA 1.6 FLEX,2010.0,NaN,AUTOMOVEL,NaN,NaN

# Eliminação de tuplas duplicadas

Antes da elimição de tuplas duplicadas no dataframe

In [7]:
antes_apagar = df.shape[0]
print("Quantidade de tuplas: ",df.shape[0])

Quantidade de tuplas:  9306

# Eliminação de tuplas duplicadas

In [8]:
df.drop_duplicates(subset=['DELEGACIA_NOME', 'ANO_BO', 'NUM_BO'], inplace=True)
df.reset_index(drop=True,inplace=True)

In [9]:
df['HORARIOOCORRENCIA'] = pd.to_datetime(df.DATAOCORRENCIA + ' ' + df.HORAOCORRENCIA)

In [10]:
df['DATAOCORRENCIA'] = pd.to_datetime(df['DATAOCORRENCIA'], format= '%Y-%m-%d') #%d-%m-%Y')

In [11]:
#Após a remoção de tuplas duplicadas
depois_apagar = df.shape[0]
print("Quantidade de tuplas: ",df.shape[0])

Quantidade de tuplas:  4277

In [12]:
df.head()

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO,QUANT_CELULAR,MARCA_CELULAR,HORARIOOCORRENCIA
0,2019,10019,10019/2019,2019-12-31 23:52:17,2020-01-01 00:06:39,2019-12-31,22:30:00,A NOITE,2019-12-31 00:00:00,2019-12-31 23:52:17,...,MG,BELO HORIZONTE,Cinza,NISSAN/VERSA 10,2018.0,2018.0,AUTOMOVEL,NaN,NaN,2019-12-31 22:30:00
1,2019,1624930,1624930/2019,2020-01-01 00:14:23,2020-01-01 00:14:02,2019-12-31,21:23:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:14:23,...,SP,NaN,Branco,NaN,NaN,NaN,AUTOMOVEL,NaN,NaN,2019-12-31 21:23:00
2,2020,2,2020-02-01 00:00:00,2020-01-01 00:17:24,2020-01-01 00:16:36,2019-12-31,22:00:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:17:24,...,NaN,NaN,Não Informado,NaN,NaN,NaN,AUTOMOVEL,NaN,NaN,2019-12-31 22:00:00
3,2020,5,2020-05-01 00:00:00,2020-01-01 00:30:31,2020-01-01 00:30:10,2019-12-31,21:15:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:30:31,...,SP,SÃO PAULO,Vermelho,I/FORD FIESTA S,2011.0,NaN,AUTOMOVEL,NaN,NaN,2019-12-31 21:15:00
4,2019,1624894,1624894/2019,2020-01-01 00:30:44,2020-01-01 00:30:37,2019-12-31,19:00:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:30:44,...,SP,SÃO PAULO,Branco,VW/KOMBI,1997.0,NaN,AUTOMOVEL,NaN,NaN,2019-12-31 19:00:00

In [13]:
df.replace(np.nan, 'Não Informado')

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO,QUANT_CELULAR,MARCA_CELULAR,HORARIOOCORRENCIA
0,2019,10019,10019/2019,2019-12-31 23:52:17,2020-01-01 00:06:39,2019-12-31,22:30:00,A NOITE,2019-12-31 00:00:00,2019-12-31 23:52:17,...,MG,BELO HORIZONTE,Cinza,NISSAN/VERSA 10,2018.0,2018.0,AUTOMOVEL,Não Informado,Não Informado,2019-12-31 22:30:00
1,2019,1624930,1624930/2019,2020-01-01 00:14:23,2020-01-01 00:14:02,2019-12-31,21:23:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:14:23,...,SP,Não Informado,Branco,Não Informado,Não Informado,Não Informado,AUTOMOVEL,Não Informado,Não Informado,2019-12-31 21:23:00
2,2020,2,2020-02-01 00:00:00,2020-01-01 00:17:24,2020-01-01 00:16:36,2019-12-31,22:00:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:17:24,...,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,AUTOMOVEL,Não Informado,Não Informado,2019-12-31 22:00:00
3,2020,5,2020-05-01 00:00:00,2020-01-01 00:30:31,2020-01-01 00:30:10,2019-12-31,21:15:00,A NOITE,2020-01-01 00:00:00,2020-01-01 00:30:31,...,SP,SÃO PAULO,Vermelho,I/FORD FIESTA S,2011.0,Não Informado,AUTOMOVEL,Não Informado,Não Informado,2019-12-31 21:15:00
4,2019,1624894,1624894/2019,2020-01-01 00:30:44,2020-01-01 00:30:37,2019-12-31,19:00:00,A NOITE,2019-12-31 00:00:00,2020-01-01 00:30:44,...,SP,SÃO PAULO,Branco,VW/KOMBI,1997.0,Não Informado,AUTOMOVEL,Não Informado,Não Informado,2019-12-31 19:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,2020,462,462/2020,2020-01-31 23:43:35,2020-01-31 23:51:13,2020-01-31,20:30:00,A NOITE,2020-01-31 00:00:00,2020-01-31 23:43:35,...,SP,S.PAULO,Branco,HONDA/CB250F TWISTER CBS,2019.0,2019.0,MOTOCICLO,Não Informado,Não Informado,2020-01-31 20:30:00
4273,2020,138403,138403/2020,2020-01-31 23:51:42,2020-01-31 23:51:17,2020-01-31,20:55:00,A NOITE,2020-01-31 00:00:00,2020-01-31 23:51:42,...,SP,DIADEMA,Prata,FIAT/IDEA ESSENCE 1.6,2014.0,Não Informado,AUTOMOVEL,Não Informado,Não Informado,2020-01-31 20:55:00
4274,2020,545,545/2020,2020-01-31 23:36:42,2020-01-31 23:52:15,2020-01-31,22:10:00,A NOITE,2020-01-31 00:00:00,2020-01-31 23:36:42,...,SP,S.PAULO,Preta,YAMAHA/FAZER YS250,2011.0,2012.0,MOTOCICLO,Não Informado,Não Informado,2020-01-31 22:10:00
4275,2020,931,931/2020,2020-01-31 23:27:40,2020-01-31 23:56:52,2020-01-31,22:15:00,A NOITE,2020-01-31 00:00:00,2020-01-31 23:27:40,...,Não Informado,Não Informado,Não Informado,Não Informado,0.0,0.0,Não Informado,Não Informado,Não Informado,2020-01-31 22:15:00
4276,2020,1096,1096/2020,2020-01-31 23:39:30,2020-01-31 23:57:46,2020-01-31,20:30:00,A NOITE,2020-01-31 00:00:00,2020-01-31 23:39:30,...,PR,CURITIBA,Branco,FORD/KA SE 1.0 SD C,2019.0,2019.0,AUTOMOVEL,Não Informado,Não Informado,2020-01-31 20:30:00

In [18]:
df.to_csv(r'C:\Users\Cassul\Desktop\trabalho_mineracao\Parte 2\csvfile_preprocessado.csv')

# Análise Exploratia dos Dados

Esta parte trabalho, consiste na utilização de técnicas estatísticas para exploração de dados, bem
como de técnicas de visualização de dados, com a finalidade de extrair conhecimento do
dataset gerado no trabalho anterior.

### Percentua de redução no dataset
Depois de eliminar os dados duplicados

In [14]:
print("Redução de: ", 100-(depois_apagar/antes_apagar)*100)

Redução de:  54.04040404040404

### Estimativa de parãmetro (Medida de tendência Central)
##### Media

In [15]:
print("Média dos roubos", df['NUM_BO'].mean())

Média dos roubos 10221.018704699556

In [16]:
print("Média:", df['NUM_BO'].mean())
print("Mediana:", df['NUM_BO'].median())
print("Desvio absoluto médio:", df['NUM_BO'].mad())
print("Variância:", df['NUM_BO'].var())
print("Desvio padrão:", df['NUM_BO'].std())
print("Moda:", df['CIDADE'].mode())

Média: 10221.018704699556
Mediana: 272.0
Desvio absoluto médio: 17453.96381119464
Variância: 2555409874.66709
Desvio padrão: 50551.06205281043
Moda: 0    S.PAULO
dtype: object